version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      PUBLIC_MINIO_URL: ${PUBLIC_MINIO_URL}
    volumes:
      - ./main.py:/app/main.py


volumes:
  minio_data: 